version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: no
    environment:
      POSTGRES_USER: billal
      POSTGRES_PASSWORD: password


volumes:
  mongo_data:
  mongo_config: